version: "3"
services:
  piwigo:
    image: tob123/piwigo
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
       - PW_VER=$VERSION
    image: tob123/piwigo:${VERSION}
    networks:
      front:
      back:
    user: apache
#    volumes:
#      - ./piw_vols/_data:/piwigo/_data
#     - ./piw_vols/local:/piwigo/local
#      - ./piw_vols/themes:/piwigo/themes
#      - ./piw_vols/template-extension:/piwigo/template-extension
#      - ./piw_vols/plugins:/piwigo/plugins
#      - ./piw_vols/upload:/piwigo/upload
#      - ./piw_vols/galleries:/piwigo/galleries
#      - pw_built:/pw_built
#      - mysqldb:/var/lib/mysql
    depends_on: 
      - piwigo-db
    healthcheck:
      test: ["CMD", "/usr/local/bin/checkcontainer_install.sh"]
    ports:
            - 8001:8001
  piwigo-db:
    image: mariadb
    networks:
      back:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD_CI}
#volumes:
#  pw_built:
#  mysqldb:
networks:
  front:
  back:
    internal: true
